name: Run pytest

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        host: ["ubuntu-latest", "macos-12"]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -e .
    - name: Test with pytest
      run: |
        pytest tests
